//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeSharpTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeSharpTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///{
        ///&quot;id&quot;: &quot;10&quot;,
        ///&quot;assetCode&quot;: &quot;BNB&quot;,
        ///&quot;assetName&quot;: &quot;Binance Coin&quot;,
        ///&quot;unit&quot;: &quot;&quot;,
        ///&quot;transactionFee&quot;: 0.23,
        ///&quot;commissionRate&quot;: 0,
        ///&quot;freeAuditWithdrawAmt&quot;: 20000,
        ///&quot;freeUserChargeAmount&quot;: 10000000,
        ///&quot;minProductWithdraw&quot;: &quot;0.460000000000000000&quot;,
        ///&quot;withdrawIntegerMultiple&quot;: &quot;0E-18&quot;,
        ///&quot;confirmTimes&quot;: &quot;30&quot;,
        ///&quot;chargeLockConfirmTimes&quot;: null,
        ///&quot;createTime&quot;: null,
        ///&quot;test&quot;: 0,
        ///&quot;url&quot;: &quot;https://etherscan.io/tx/&quot;,
        ///&quot;addressUrl&quot;: &quot;https://etherscan.io/address/&quot;,
        ///&quot;blockUrl&quot;: &quot;https://etherscan.io/blocks/&quot;,
        ///&quot;enableCharge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BinanceGetAllAssets {
            get {
                return ResourceManager.GetString("BinanceGetAllAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;BTC_AMP&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:53458743},&quot;BTC_ARDR&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:40603963},&quot;BTC_BCN&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:10872588},&quot;BTC_BCY&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:28184309},&quot;BTC_BLK&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:23874966},&quot;BTC_BTCD&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:25198804},&quot;BTC_BTM&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:20151600},&quot;BTC_BTS&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:67659413},&quot;BTC_BURST&quot;:{ [rest of string wa....
        /// </summary>
        internal static string PoloniexGetSymbolsMetadata1 {
            get {
                return ResourceManager.GetString("PoloniexGetSymbolsMetadata1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;BTC_AMP&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:53458743},&quot;BTC_ARDR&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:40603963},&quot;BTC_BCH&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:106056864},&quot;BTC_BCN&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:10872588},&quot;BTC_BCY&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:28184309},&quot;BTC_BLK&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:23874966},&quot;BTC_BTCD&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:25198804},&quot;BTC_BTM&quot;:{&quot;asks&quot;:[],&quot;bids&quot;:[],&quot;isFrozen&quot;:&quot;0&quot;,&quot;seq&quot;:20151600},&quot;BTC_BTS&quot;:{&quot; [rest of stri....
        /// </summary>
        internal static string PoloniexGetSymbolsMetadata2 {
            get {
                return ResourceManager.GetString("PoloniexGetSymbolsMetadata2", resourceCulture);
            }
        }
    }
}
